default_language_version:
  python: python3.12

repos:
  # Python hooks for the extractor
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements
        files: ^(fpl2sql-extractor/|fpl2sql-frontend/)
      - id: trailing-whitespace
        files: ^(fpl2sql-extractor/|fpl2sql-frontend/)
      - id: check-yaml
        files: ^fpl2sql-extractor/
      - id: check-builtin-literals
        files: ^(fpl2sql-extractor/|fpl2sql-frontend/)
      - id: end-of-file-fixer
        files: ^(fpl2sql-extractor/|fpl2sql-frontend/)
      - id: check-ast
        files: ^fpl2sql-extractor/
      - id: check-docstring-first
        files: ^fpl2sql-extractor/

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
          - "--line-length"
          - "120"
          - "--lines-after-imports"
          - "2"
          - "--lines-between-types"
          - "1"
          - "--atomic"
        files: ^fpl2sql-extractor/

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args:
          - "--line-length"
          - "120"
        files: ^fpl2sql-extractor/

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length"
          - "120"
          - "--ignore"
          - "E231,E702"
        files: ^fpl2sql-extractor/

  # Local hook for mypy
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy fpl2sql-extractor --cache-dir=/dev/null
        language: system
        pass_filenames: false

  # JavaScript hooks for the frontend
  - repo: local
    hooks:
      - id: lint
        name: ESLint
        entry: sh -c "cd fpl2sql-frontend && npm run lint"
        language: system

      - id: format
        name: Prettier
        entry: sh -c "cd fpl2sql-frontend && npm run check-format"
        language: system
