# generated by datamodel-codegen:
#   filename:  bootstrap.json
#   timestamp: 2024-09-20T10:13:26+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ChipPlay(BaseModel):
    chip_name: str
    num_played: int


class TopElementInfo(BaseModel):
    id: int
    points: int


class Event(BaseModel):
    id: int
    name: str
    deadline_time: str
    release_time: None
    average_entry_score: int
    finished: bool
    data_checked: bool
    highest_scoring_entry: Optional[int] = None
    deadline_time_epoch: int
    deadline_time_game_offset: int
    highest_score: Optional[int] = None
    is_previous: bool
    is_current: bool
    is_next: bool
    cup_leagues_created: bool
    h2h_ko_matches_created: bool
    ranked_count: int
    chip_plays: List[ChipPlay]
    most_selected: Optional[int] = None
    most_transferred_in: Optional[int] = None
    top_element: Optional[int] = None
    top_element_info: Optional[TopElementInfo] = None
    transfers_made: int
    most_captained: Optional[int] = None
    most_vice_captained: Optional[int] = None


class GameSettings(BaseModel):
    league_join_private_max: int
    league_join_public_max: int
    league_max_size_public_classic: int
    league_max_size_public_h2h: int
    league_max_size_private_h2h: int
    league_max_ko_rounds_private_h2h: int
    league_prefix_public: str
    league_points_h2h_win: int
    league_points_h2h_lose: int
    league_points_h2h_draw: int
    league_ko_first_instead_of_random: bool
    cup_start_event_id: None
    cup_stop_event_id: None
    cup_qualifying_method: None
    cup_type: None
    featured_entries: List
    percentile_ranks: List[int]
    squad_squadplay: int
    squad_squadsize: int
    squad_team_limit: int
    squad_total_spend: int
    ui_currency_multiplier: int
    ui_use_special_shirts: bool
    ui_special_shirt_exclusions: List
    stats_form_days: int
    sys_vice_captain_enabled: bool
    transfers_cap: int
    transfers_sell_on_fee: float
    max_extra_free_transfers: int
    league_h2h_tiebreak_stats: List[str]
    timezone: str


class Phase(BaseModel):
    id: int
    name: str
    start_event: int
    stop_event: int
    highest_score: Optional[int] = None


class Team(BaseModel):
    code: int
    draw: int
    form: None
    id: int
    loss: int
    name: str
    played: int
    points: int
    position: int
    short_name: str
    strength: int
    team_division: None
    unavailable: bool
    win: int
    strength_overall_home: int
    strength_overall_away: int
    strength_attack_home: int
    strength_attack_away: int
    strength_defence_home: int
    strength_defence_away: int
    pulse_id: int


class Element(BaseModel):
    chance_of_playing_next_round: Optional[int] = None
    chance_of_playing_this_round: Optional[int] = None
    code: int
    cost_change_event: int
    cost_change_event_fall: int
    cost_change_start: int
    cost_change_start_fall: int
    dreamteam_count: int
    element_type: int
    ep_next: str
    ep_this: str
    event_points: int
    first_name: str
    form: str
    id: int
    in_dreamteam: bool
    news: str
    news_added: Optional[str] = None
    now_cost: int
    photo: str
    points_per_game: str
    second_name: str
    selected_by_percent: str
    special: bool
    squad_number: None
    status: str
    team: int
    team_code: int
    total_points: int
    transfers_in: int
    transfers_in_event: int
    transfers_out: int
    transfers_out_event: int
    value_form: str
    value_season: str
    web_name: str
    region: Optional[int] = None
    minutes: int
    goals_scored: int
    assists: int
    clean_sheets: int
    goals_conceded: int
    own_goals: int
    penalties_saved: int
    penalties_missed: int
    yellow_cards: int
    red_cards: int
    saves: int
    bonus: int
    bps: int
    influence: str
    creativity: str
    threat: str
    ict_index: str
    starts: int
    expected_goals: str
    expected_assists: str
    expected_goal_involvements: str
    expected_goals_conceded: str
    influence_rank: int
    influence_rank_type: int
    creativity_rank: int
    creativity_rank_type: int
    threat_rank: int
    threat_rank_type: int
    ict_index_rank: int
    ict_index_rank_type: int
    corners_and_indirect_freekicks_order: Optional[int] = None
    corners_and_indirect_freekicks_text: str
    direct_freekicks_order: Optional[int] = None
    direct_freekicks_text: str
    penalties_order: Optional[int] = None
    penalties_text: str
    expected_goals_per_90: float
    saves_per_90: float
    expected_assists_per_90: float
    expected_goal_involvements_per_90: float
    expected_goals_conceded_per_90: float
    goals_conceded_per_90: float
    now_cost_rank: int
    now_cost_rank_type: int
    form_rank: int
    form_rank_type: int
    points_per_game_rank: int
    points_per_game_rank_type: int
    selected_rank: int
    selected_rank_type: int
    starts_per_90: float
    clean_sheets_per_90: float


class ElementStat(BaseModel):
    label: str
    name: str


class ElementType(BaseModel):
    id: int
    plural_name: str
    plural_name_short: str
    singular_name: str
    singular_name_short: str
    squad_select: int
    squad_min_select: None
    squad_max_select: None
    squad_min_play: int
    squad_max_play: int
    ui_shirt_specific: bool
    sub_positions_locked: List[int]
    element_count: int


class Bootstrap(BaseModel):
    events: List[Event]
    game_settings: GameSettings
    phases: List[Phase]
    teams: List[Team]
    total_players: int
    elements: List[Element]
    element_stats: List[ElementStat]
    element_types: List[ElementType]
