# generated by datamodel-codegen:
#   filename:  fixtures.json
#   timestamp: 2024-09-20T10:14:00+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, RootModel


class AItem(BaseModel):
    value: int
    element: int


class HItem(BaseModel):
    value: int
    element: int


class Stat(BaseModel):
    identifier: str
    a: List[AItem]
    h: List[HItem]


class Fixture(BaseModel):
    code: int
    event: int
    finished: bool
    finished_provisional: bool
    id: int
    kickoff_time: str
    minutes: int
    provisional_start_time: bool
    started: bool
    team_a: int
    team_a_score: Optional[int] = None
    team_h: int
    team_h_score: Optional[int] = None
    stats: List[Stat]
    team_h_difficulty: int
    team_a_difficulty: int
    pulse_id: int


class Fixtures(RootModel[List[Fixture]]):
    root: List[Fixture]
